CREATE TABLE LOGIN_USER
(
  USER_ID INT NOT NULL,
  PASSWORD VARCHAR(MAX) NOT NULL,
  FIRST_NAME VARCHAR(10) NOT NULL,
  LAST_NAME VARCHAR(10) NOT NULL,
  BIRTH_DAY INT NULL,
  AUTH BIT NOT NULL,
  PRIMARY KEY(USER_ID)
);